#!/bin/bash

git_clone() {
    echo -n "$2: "
    if pushd $2; then
        git pull
        popd
    else
        git clone $1 $2
    fi
}

pushd $(pwd)

git_clone git@github.com:vim-airline/vim-airline.git ~/.vim/bundle/vim-airline
git_clone git@github.com:altercation/vim-colors-solarized.git ~/.vim/bundle/vim-colors-solarized

git_clone git@github.com:vim-erlang/vim-erlang-runtime.git ~/.vim/bundle/vim-erlang-runtime
git_clone git@github.com:vim-erlang/vim-erlang-compiler.git ~/.vim/bundle/vim-erlang-compiler
git_clone git@github.com:vim-erlang/vim-erlang-tags.git ~/.vim/bundle/vim-erlang-tags

git_clone git@github.com:elixir-lang/vim-elixir.git ~/.vim/bundle/vim-elixir

git_clone git@github.com:EinfachToll/DidYouMean.git ~/.vim/bundle/DidYouMean
git_clone git@github.com:kien/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim

git_clone git@github.com:tpope/vim-unimpaired.git ~/.vim/bundle/vim-unimpaired

git_clone git@github.com:airblade/vim-gitgutter.git ~/.vim/bundle/vim-gitgutter

popd

# Using the explicit path for ls prevents it from using the alias
# (i.e. it turns off -F).
/bin/ls -1d */ > ~/.vim/bundle/.gitignore
