#!/bin/sh

# scons
mkdir -p scons/syntax
wget 'http://www.vim.org/scripts/download_script.php?src_id=6421' -O scons/syntax/scons.vim

# Makeshift
git clone git://github.com/johnsyweb/vim-makeshift.git

# fugitive.vim
git clone git://github.com/tpope/vim-fugitive.git

# vim: ft=sh
