#!/bin/sh

# scons
mkdir -p scons/syntax
wget 'http://www.vim.org/scripts/download_script.php?src_id=6421' -O scons/syntax/scons.vim

# Makeshift
git clone git://github.com/johnsyweb/vim-makeshift.git

# fugitive.vim
git clone git://github.com/tpope/vim-fugitive.git

# Unimpaired
git clone git://github.com/tpope/vim-unimpaired.git

# Syntastic
git clone https://github.com/scrooloose/syntastic.git

# jade
git clone https://github.com/digitaltoad/vim-jade.git

# JavaScript
git clone https://github.com/pangloss/vim-javascript.git

# Beautify
git clone https://github.com/maksimr/vim-jsbeautify.git

# Django
mkdir -p django/syntax
wget 'http://www.vim.org/scripts/download_script.php?src_id=17736' -O django/syntax/django.vim
wget 'http://www.vim.org/scripts/download_script.php?src_id=6678' -O django/syntax/htmldjango.vim

# vim: ft=sh
