" This MUST come first
set nocompatible

" Use pathogen for managing plugins. This must come fairly near the top.
execute pathogen#infect()

" Current directory follows active file.
autocmd BufEnter * silent! lcd %:p:h

if !exists("g:os")
  if has("unix")
    let g:os = substitute(system('uname'), '\n', '', '')
  endif
endif

" Include other stuff
source ~/.vim/startup/size.vim
source ~/.vim/startup/term.vim
source ~/.vim/startup/keybindings.vim
source ~/.vim/startup/selection.vim
source ~/.vim/startup/tabcomplete.vim
source ~/.vim/startup/toolbar.vim
source ~/.vim/startup/statusbar.vim
source ~/.vim/startup/whitespace.vim
source ~/.vim/startup/linenumbers.vim

source ~/.vim/startup/filetype.vim
source ~/.vim/startup/indent.vim
source ~/.vim/startup/tabs.vim

" vim: set ft=vim:
